Disable nant test as currently can't install nant on the Windows agent
Downloading nant
  from 'https://downloads.sourceforge.net/project/nant/nant/0.92/nant-0.92-bin.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://downloads.sourceforge.net/project/nant/nant/0.92/nant-0.92-bin.zip'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."

Need to fix this.